*&---------------------------------------------------------------------*
*&  INCLUDE           ZFI_P100_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK BL1 WITH FRAME TITLE TEXT-000.                          " BLOCK OLARAK AÇýLAN SELECTION SCREEN

SELECT-OPTIONS :
        S_ST FOR CMACBPST-STUDENT12 NO INTERVALS,                                       " ÖÐRENCI NUMARASý ALMAK IÇIN SELECT OPTION - ARALýK DEÐER GIRILEMEYECEK
        S_PRDNI  FOR  BAPISTUDENT_PERSONAL-PERSIDNO NO INTERVALS,                       " TC NO ALMAK IÇIN SELECT OPTION - ARALýK DEÐER GIRILEMEYECEK
        S_FAC FOR ZSM_TUR_ORG-ORGKODU MATCHCODE OBJECT ZSM_TUR_ORG_F_SH_2 NO INTERVALS. " FAKÜLTEYE GÖRE SORGU YAPMAK IÇIN ALýNACAK SELECT OPTION - ARALýK DEÐER GIRILEMEYECEK
SELECTION-SCREEN END OF BLOCK BL1 .                                                     " BLOCK SONU

SELECTION-SCREEN BEGIN OF BLOCK BL2 WITH FRAME TITLE TEXT-001.                          " BLOCK OLARAK AÇýLAN SELECTION SCREEN

PARAMETERS : P_PERSL  TYPE  CMACDB_FEEHD-PERSL OBLIGATORY,                              " DÖNEM ANAHTARý
             P_TDONEM TYPE  ZCAS_OGRENCI_FATURALAMA-TDONEM OBLIGATORY,                  " TAKSIT DÖNEMI
             P_DATUM  TYPE SY-DATUM OBLIGATORY,                                         " FATURA BASýLACAK GÜNÜN TARIHI
             P_IPTAL  AS CHECKBOX.                                                      " ÝPTAL EDÝLECEK ÖÐRENCÝLER

SELECTION-SCREEN END OF BLOCK BL2 .                                                     " AÇILAN BLOCK SONU

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_ST-LOW.                                      " ÖÐRENCI NO SELECT OP. LOW DEÐERI DEÐIÞIRSE TETIKLENECEK OLAYDýR

  PERFORM GET_STUDENT_SEARCHHELP CHANGING S_ST-LOW.                                     " S_ST-LOW DEÐERI DEÐIÞIMINDE ÇALýÞACAK PERFORMDUR

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_ST-HIGH.                                     " ÖÐRENCI NO SELECT OP. HIGH DEÐERI DEÐIÞIRSE TETIKLENECEK OLAYDýR

  PERFORM GET_STUDENT_SEARCHHELP CHANGING S_ST-HIGH.                                    " S_ST-HIGH DEÐERI DEÐIÞIMINDE ÇALýÞACAK PERFORMDUR
