*&---------------------------------------------------------------------*
*&  Include           ZFI_R115_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

SELECT-OPTIONS : S_STNO  FOR ZSM_STDNT_SEARCH-STUDENT_NO  NO INTERVALS,
                 S_FAK   FOR ZSM_STDNT_SEARCH-FACULTY_ID  NO INTERVALS,
                 S_KAYIT FOR ZSM_STDNT_SEARCH-KAYIT_YILI  NO INTERVALS,
                 S_KAYDN FOR ZSM_STDNT_SEARCH-KAYIT_DONEM NO INTERVALS MATCHCODE OBJECT HRPIQ00CMPR_GET_PERID.

SELECTION-SCREEN END OF BLOCK B1.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_FAK-LOW.

  PERFORM FAKULTY_SH.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_STNO-LOW.

  PERFORM STUNO_SH.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_KAYIT-LOW.

  PERFORM PERYR_SH.
